baseURL = "https://denhoff.ca/"
languageCode = "en-us"
title = "Phil Denhoff"

theme = "denhoff"
relativeURLs = true

[params]
    description = "A personal blog & landing page" 
    keywords = "blog,developer,personal" # site keywords
    themeColor = "theme-base-0c"
    footerText = "Made by yours truly, in 2018, in Victoria, BC."
    firstName = "Phil"
    lastName = "Denhoff"

# Menu links
[[menu.main]]
    name = "About Me"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Start"
    weight = 3
    url = "/start"
