baseURL = "https://denhoff.ca/"
languageCode = "en-us"
title = "Phil Denhoff"

theme = "hyde"

[params]
    description = "A personal blog & landing page" 
    keywords = "blog,developer,personal" # site keywords
    themeColor = "theme-base-0c"
    
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Start"
    weight = 3
    url = "/start"
