baseURL = "https://denhoff.ca/"
languageCode = "en-us"
title = "Phil Denhoff"

theme = "denhoff"
relativeURLs = true

[params]
    description = "A personal blog & landing page"
    keywords = "blog,developer,personal"
    themeColor = "theme-base-0c"
    footerText = "Made in Victoria, BC. 🥑"
    firstName = "Phil"
    lastName = "Denhoff"

# Menu links
[[menu.main]]
    name = "About Me"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Tools"
    weight = 3
    url = "/tools"

[markup.goldmark.renderer]
unsafe= true
